# Generated by Django 3.1.7 on 2021-06-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210612_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
